### ISSUE TITLE
Is beta-vorticity removed from PV when inverting for psi?

### ISSUE THREAD

**Issue by roxyboy** [jejjohnson/somax#11]
I've been checking when beta-planetary vorticity should be added or not but I'm wondering if `q_i` [here](https://github.com/jejjohnson/somax/blob/8d29ffe2f5cd48168b0fa8192d81caa9dd182384/somax/_src/models/qg/operators.py#L196) has it removed prior to inverting for the streamfunction...

Mathematically, it should be removed as is done in [MQGeometry](https://github.com/louity/MQGeometry/blob/f36617c4a89eab2891bc7c90b3eceb9c808452c1/qgm.py#L159).

If not, it could be the cause for the meridional asymmetry we're seeing for symmetrical wind-stress curl.
![Screenshot 2024-01-02 at 1 00 13 PM](https://github.com/jejjohnson/somax/assets/8934026/c7f85d8e-d81d-4a04-9a90-2235b6d81b5f)

**Comment by jejjohnson** [comment]
I see what you mean… I don't think it was removed. 

You’re saying that one should only have the laplacian psi and psi terms when doing the inversion for psi?

**Comment by roxyboy** [comment]
> You’re saying that one should only have the laplacian psi and psi terms when doing the inversion for psi?

Yep. I'm working on it now to see if fixing this works :)

**Comment by roxyboy** [comment]
PR #12 addressed this.
